### ISSUE TITLE
Wrong entries in ArangoDB

### ISSUE THREAD

**Issue by severindellsperger** [cisco-open/jalapeno#63] opened 2022-10-18 11:58 UTC
Sometimes documents in ArangoDB contain wrong entries. In the following example, the `_from` and `_to` values are incorrect and show the same information (the remaining values of the document are correct) :

![wrong-entry-ls_node_edge](https://user-images.githubusercontent.com/6859126/196421045-97e0a88b-33d2-4823-9fb1-8868160a9040.png)

The reason for these wrong entries is not clear. Maybe there is a problem with an update of the documents.

**Comment by brmcdoug** [comment] 2022-10-18 15:39
Hi Serverin, can you send me the two ls_link entries referenced in the _key? I suspect maybe the code is making a mistake dealing with ISIS level-1/level-2 links.

**Comment by severindellsperger** [comment] 2022-10-18 16:04
I think we only have one link (because only L2 links):
```
RP/0/RP0/CPU0:XR-1#sh isis nei | inc XR-2
XR-2           Gi0/0/0/2        *PtoP*         Up    27       L2   Capable

```

Anyway, here are the information:
```
{
  "action": "add",
  "router_hash": "4641ab6dd73c54b3f739151753e3928a",
  "router_ip": "2001:db8:4444::4",
  "domain_id": 0,
  "peer_hash": "1a505111d3406942f38c987c6bcd1dc7",
  "peer_ip": "2001:db8:8888::8",
  "peer_asn": 64097,
  "timestamp": "2022-10-08T13:04:08.000973385Z",
  "igp_router_id": "0000.0000.0001",
  "protocol": "IS-IS Level 2",
  "protocol_id": 2,
  "area_id": "0",
  "nexthop": "2001:db8:8888::8",
  "mt_id_tlv": {
    "a_flag": false,
    "mt_id": 2,
    "o_flag": false
  },
  "local_link_id": 10,
  "remote_link_id": 8,
  "local_link_ip": "2001:db8:12::1",
  "remote_link_ip": "2001:db8:12::2",
  "igp_metric": 2,
  "max_link_bw": 1000000000,
  "remote_node_hash": "e3101c1ec751c1f840c76322b4013657",
  "local_node_hash": "20595461e6bc8910afecb7b11c904a1e",
  "remote_igp_router_id": "0000.0000.0002",
  "local_node_asn": 64097,
  "remote_node_asn": 64097,
  "srv6_endx_sid": [
    {
      "endpoint_behavior": 57,
      "flags": {
        "b_flag": false,
        "s_flag": false,
        "p_flag": false
      },
      "sid": "fc00:0:1:e000::",
      "sub_tlvs": [
        {
          "type": 1252,
          "length": 8,
          "locator_block_length": 32,
          "locator_node_length": 16,
          "function_length": 16,
          "argument_length": 0
        }
      ]
    }
  ]
}
```

**Comment by severindellsperger** [comment] 2022-10-19 08:18
Can it maybe be related because we have several RRs?

**Comment by ILLIDOM** [comment] 2022-10-19 14:29
Hi Bruce, I tested the behavior of wrong "_from" and "_to" keys today. It seems like the issue is only present in two cases. First when the whole Jalapeno stack is coming up for the first time. (I was able to get the correct entries inside ls_node_edge by deleting the collection first and then restarting the lslinknode-edge pod). In this case no ls_node or ls_link events are being processed by the lslink_edge processor so no problems with wrong entries.

The second case is if a whole node is removed from the topology. (When removing only links the entries inside ls_node_edge were still correct). I will still look further into the issue but help from your side would be very much appreciated.

Thanks!

**Comment by brmcdoug** [comment] 2022-10-19 16:05
Hi guys, I just created a debug lslink_edge image called "iejalapeno/linkstate-edge:debug-ls". Can you install the image and re-create the issue (remove whole node) and send me the logs?

**Comment by ILLIDOM** [comment] 2022-10-19 18:11
Hi Bruce, 
Thanks for your quick reply. I will test it out tomorrow and send you the logs of the linkstate-edge service as well as dumps from the ArangoDB before and after the removal of the node.

**Comment by ILLIDOM** [comment] 2022-11-07 12:29
I think this Issue can be marked as solved and closed. The issue was using the wrong image due to a renaming after the project went open source.

**Closed** 2022-11-07 16:04 UTC
